import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>QR Scanner & Generator</h1>
        <hr height="1px" width="40%"/>
        <h2 className={styles.description}>Traceability System - PT Gaya Green Srikandi</h2>

        <div className={styles.grid}>
          <Link href="/scan" className={styles.card}>
            <a>
              <h2>Scan a qr code&rarr;</h2>
            </a>
          </Link>
          {"    "}
          <a><h2>&ensp; | &ensp;</h2></a>
          <Link href="/generate" className={styles.card}>
            <a>
              <h2> Generate a qr code&rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  );
}
